config.code=232323
config.username=alessa
config.message=oh hai markñññ
config.listOfValues=1,2,3,4
config.valuesMap={product:"Cpu intel corei7", description: "Alder lake, 12 core, 5GHz", price: '1000'}
